<Project>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="0.10.0" />
    <PackageVersion Include="Avalonia.Controls.DataGrid" Version="0.10.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="0.10.0" />
    <PackageVersion Include="Avalonia.ReactiveUI" Version="0.10.0" />
    <PackageVersion Include="Avalonia.Xaml.Behaviors" Version="0.10.0" />
    <PackageVersion Include="AvaloniaUIRibbon" Version="1.0.5-beta" />
    <PackageVersion Include="Dropbox.Api" Version="6.0.1" />
    <PackageVersion Include="FluentFTP" Version="33.0.3" />
    <PackageVersion Include="AWSSDK.S3" Version="3.5.7.12" />
    <PackageVersion Include="Google.Apis.Drive.v3" Version="1.49.0.2201" />
    <PackageVersion Include="Google.Apis.Oauth2.v2" Version="1.49.0.1869" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageVersion Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageVersion Include="RestSharp" Version="106.11.7" />
    <PackageVersion Include="RestSharp.Serializers.NewtonsoftJson" Version="106.11.7" />
    <PackageVersion Include="SkiaSharp" Version="2.88.9" />
  </ItemGroup>
</Project>